### ISSUE TITLE
Flutter web Not working on Version2.0.0  Error: NoSuchMethodError: 'split'

### ISSUE THREAD

**Issue by zhaodianbo** [rikulo/socket.io-client-dart#289]
my code：  
   IO.Socket socket = IO.io('http://127.0.0.1:9996');
    socket.onConnect((_) {
      print('connect');
    });
    socket.on('read', (data) => print(data));
    socket.onDisconnect((_) => print('disconnect'));

output：
Error: NoSuchMethodError: 'split'
Dynamic call of null.
Receiver: Instance of 'NativeUint8List'
Arguments: ["\u001e"]
    at Object.throw_ [as throw] (http://localhost:59482/dart_sdk.js:5080:11)
    at Object.defaultNoSuchMethod (http://localhost:59482/dart_sdk.js:5506:15)
    at Uint8Array.noSuchMethod (http://localhost:59482/dart_sdk.js:6619:19)
    at Object.noSuchMethod (http://localhost:59482/dart_sdk.js:5503:30)
    at callNSM (http://localhost:59482/dart_sdk.js:5242:19)
    at Object._checkAndCall (http://localhost:59482/dart_sdk.js:5244:27)
    at Object.callMethod (http://localhost:59482/dart_sdk.js:5322:17)
    at Object.dsend (http://localhost:59482/dart_sdk.js:5325:17)
    at PacketParser.decodePayload (http://localhost:59482/packages/socket_io_common/src/engine/parser/parser.dart.lib.js:250:33)
    at xhr_transport.XHRTransport.new.onData (http://localhost:59482/packages/socket_io_client/src/engine/transport/xhr_transport.dart.lib.js:423:38)
    at http://localhost:59482/packages/socket_io_client/src/engine/transport/xhr_transport.dart.lib.js:580:14
    at Object._checkAndCall (http://localhost:59482/dart_sdk.js:5279:16)
    at Object.dcall (http://localhost:59482/dart_sdk.js:5284:17)
    at http://localhost:59482/packages/socket_io_common/src/util/event_emitter.dart.lib.js:47:14
    at [dartx.forEach] (http://localhost:59482/dart_sdk.js:17202:11)
    at xhr_transport.Request.new.emit (http://localhost:59482/packages/socket_io_common/src/util/event_emitter.dart.lib.js:46:39)
    at xhr_transport.Request.new.onData (http://localhost:59482/packages/socket_io_client/src/engine/transport/xhr_transport.dart.lib.js:828:12)
    at xhr_transport.Request.new.onLoad (http://localhost:59482/packages/socket_io_client/src/engine/transport/xhr_transport.dart.lib.js:885:14)
    at http://localhost:59482/packages/socket_io_client/src/engine/transport/xhr_transport.dart.lib.js:807:18
    at Object._checkAndCall (http://localhost:59482/dart_sdk.js:5279:16)
    at Object.dcall (http://localhost:59482/dart_sdk.js:5284:17)
    at XMLHttpRequest.<anonymous> (http://localhost:59482/dart_sdk.js:109003:100)

flutter --version
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (3 months ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2

It work fine when version change to  socket_io_client: 1.0.2

**Comment by hatemragab** [comment]
this happens when you set headers to the split bug in node js becouse cant read the access token from the header you should use this for flutter web 
```
  Socket getSocket() {
    return io(
      ApiConstants.baseServerIp,
      OptionBuilder()
          .enableAutoConnect()
          .setQuery({
            "auth":
                "Bearer ${AppPref.getHashedString(key: StorageKeys.accessToken)}",
          })
          .setExtraHeaders({
            'Authorization':
                "Bearer ${AppPref.getHashedString(key: StorageKeys.accessToken)}",
            "accept-language": "en"
          })
          .enableForceNew()
          .enableForceNewConnection()
          .enableReconnection()
          .setTimeout(5000)
          .setReconnectionDelay(5000)
          .setTransports(['websocket'])
          .build(),
    );
  }
```
