### ISSUE TITLE
Mutliple arguments when Ack

### ISSUE THREAD

**Issue by Oskang09** [rikulo/socket.io-client-dart#21]
Trying to get work with [featherjs](https://feathersjs.com) and unable to work with the direct connection given at documentation.

Worked well after make this fix. 
( L150, lib/src/socket.dart )
```
// But would break other data type
List sendData = data === null ? [event] : [event, ...data];
```

Example code:
```
_socket.emitWithAck('get', [ 'product', 78 ],
            ack: (error, data) {
                print(error);
            });
```

```
_socket.emitWIthAck('find', [ 'product' ], 
            ack: (error, data) {
                print(error);
            });
```

And also for arguments when success feathers only return error & data, when error only receive error and dart would throw error.

Error Message:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: Closure call with mismatched arguments: function 'call'
```

**Comment by jumperchen** [comment]
FYI: Spread operator only works on Dart 2.3, but our internal project still works with Dart 2.1.

**Comment by Oskang09** [comment]
I think this work too for concat values

```
[].add(event)..addAll(data)
```
